[package]
name = "risingwave_cmd"
version = "0.1.12"
edition = "2021"

[features]
static-link = ["workspace-static-link"]

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
log = { version = "0.4", features = ["release_max_level_info"] }
risingwave_compactor = { path = "../storage/compactor" }
risingwave_compute = { path = "../compute" }
risingwave_ctl = { path = "../ctl" }
risingwave_frontend = { path = "../frontend" }
risingwave_meta = { path = "../meta" }
risingwave_rt = { path = "../utils/runtime" }
stats_alloc = "0.1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
    "tracing",
] }
tracing = { version = "0.1", features = ["release_max_level_info"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
workspace-static-link = { path = "../utils/static-link", optional = true, features = ["enabled"] }

[[bin]]
name = "frontend"
path = "src/bin/frontend_node.rs"

[[bin]]
name = "meta-node"
path = "src/bin/meta_node.rs"

[[bin]]
name = "compute-node"
path = "src/bin/compute_node.rs"

[[bin]]
name = "compactor"
path = "src/bin/compactor.rs"

[[bin]]
name = "risectl"
path = "src/bin/ctl.rs"
